name: Run Tests with Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Tests
        run: |
          docker compose up --abort-on-container-exit --exit-code-from tests

      - name: Clean up
        if: always()
        run: |
          docker compose down -v
